# Generated by Django 2.1.1 on 2018-09-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='Director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='Genero',
            new_name='genero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='.../img/'),
        ),
    ]
